language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "Nothing to be installed..."

before_script:
  - echo "Carrying out no tests..."

script:
  - docker --version
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user bmckay900/udagram-api-user:v2
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed bmckay900/udagram-api-feed:v2
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend bmckay900/udagram-frontend:v2
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy bmckay900/reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bmckay900/udagram-api-user:v2
  - docker push bmckay900/udagram-api-feed:v2
  - docker push bmckay900/udagram-frontend:v2
  - docker push bmckay900/reverseproxy:v2
